/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// import java.sql.SQLException;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    var dbh = new DBHandle();
    var ui = new UI();
    System.out.println("Enter your information to add your account information to the database.");
    String[] values = ui.inputQuery();
    String[] fields = { "first_name", "last_name", "email", "password" };
    dbh.add("info", fields, values);
    System.out.println("Added your information to our database. Thank You !");

  }
}
