--INSERT INTO info (first_name, last_name, email, password) VALUES
--('John', 'Doe', 'john.doe@example.com', 'password123'),
--('Jane', 'Smith', 'jane.smith@example.com', 'securePassword!1'),
--('Mike', 'Johnson', 'mike.johnson@example.com', '12345password'),
--('Emily', 'Davis', 'emily.davis@example.com', 'emilyPassword@2025'),
--('Chris', 'Brown', 'chris.brown@example.com', 'chrisPass!2'),
--('Anna', 'Wilson', 'anna.wilson@example.com', 'annaW1234'),
--('David', 'Moore', 'david.moore@example.com', 'davidMoore!5'),
--('Sophia', 'Taylor', 'sophia.taylor@example.com', 'SophiaPass#2'),
--('James', 'Anderson', 'james.anderson@example.com', 'James2025!'),
--('Olivia', 'Thomas', 'olivia.thomas@example.com', 'Olivia@123');
--
select * from info;
