name: Java CI with Maven + SonarCloud

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, Test & Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with JaCoCo test coverage
        run: mvn clean verify -DskipTests=false
        working-directory: ./Xpert/Backend

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./Xpert/Backend
          args: >
            -Dsonar.projectKey=Learnathon-By-Geeky-Solutions_bytebuilders-
            -Dsonar.organization=learnathon-by-geeky-solutions
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.exclusions=src/main/java/com/xpert/**/*
            -Dsonar.coverage.inclusions=src/main/java/com/xpert/service/impl/**/*.java
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
